### ISSUE TITLE
Briarwood

### ISSUE THREAD

**Issue by lesleynewman** [sycacorp/sycacorp#1]
1.   Briarwood descriptions:  take out the word "safe".  Using this sets up a huge liability for us.

2,  Briarwood Terrace description, first paragraph last sentence is repeated again in the second paragraph.  Take out last sentence in first paragraph.

3.   Briarwood descriptions  it says views of Bellingham, we should change that to something like "natural, quiet setting" or "parklike setting" "suburban landscaping" but there are no longer views from those back patios.

4.  Briarwood descriptions, take out the word "family" when describing the room.  Use the word "bonus" room.  In that same description we should note that only the 3 bedrooms have the downstairs bonus room.  

5.  Blueberry:  Add a few more descriptions on Blueberry (bullet points like on Briarwood) rather than one big paragraph?

6. 12th St. Village:  should take out "designated parking spot" since we don't actually give them a specific spot and parking is such an issue there.

7.  1514 12th St.:  An incorrect spelling.  Donavan should be spelled "Donovan"

8.  Under Branding Scheme, I would omit the word "The" and start the paragraph with "Bellingham Bay ...."

9.  Under "Hey There, Hamster" ... at the bottom it only lists 12th St. Village?  Should the other property addresses be listed or take it out completely?

10.  Under Rental Policy:  We do not ask for a 2nd piece of ID.  Driver's License or government issued photo ID is good enough.

11.  Under Rental Policy: Take out the last sentence under "Clean Criminal Record" - "This includes, but ......" 

I will continue to look it over but this is what stood out to me right now.

**Comment by tofutim** [comment]
I've gone ahead and made all the changes. Except:

> Under "Hey There, Hamster" ... at the bottom it only lists 12th St. Village? Should the other property addresses be listed or take it out completely?

That is a photo label. If you look at the other photos you'll see what I mean.

**Comment by lesleynewman** [comment]
Great.  Oh, now I understand why the address is there.   I think the
website is very professional.  The boys did a wonderful job, I appreciate
their effort.
